require("settings")
require("plugins")
require("colorschemes.nightfox")
-- require('colorschemes.gruvbox')
require("mappings")
require("ale")
require("lsp-config.lang-servers")
require("ac.nvim-cmp")
require("airline")
