require("settings")
require("plugins")
-- require("colorschemes.nightfox")
-- require("colorschemes.gruvbox")
require("colorschemes.gruvbox_material")
require("mappings")
require("ale")
require("lsp-config.lang-servers")
require("ac.nvim-cmp")
require("nvim-lualine")
require("nvim-telescope")
